var GAME_LEVELS = [
  ["                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                              o                                                  ",
   "                                             o o                                                 ",
   "                                            xxxxx                                    o           ",
   "                                                                                    o o          ",
   "                                     xxxxxxx     xxxxxxx                                         ",
   "                   o                 x     x!!!!!x     x        o       xxx                      ",
   " @                 o                 x     x!!!!!x     x        o                                ",
   "xxxxxxxxx     xxxxxxxxxxx    xxxxxxxxx     xxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxx",
   "        x!!!!!x         x!!!!x                                                   x!!!!!x         ",
   "        x!!!!!x         x!!!!x                                                   x!!!!!x         ",
   "        x!!!!!x         xxxxxx                                                   x!!!!!x         ",
   "        x!!!!!x                                                                  xxxxxxx         ",
   "        xxxxxxx                                                                                  ",
   "                                                                                                 "],
   ["                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "               ooo                                                                                  ",
    "              xxxxx                                                                                 ",
    "              x!!!x      xxx                                                                        ",
    "              x!!!x                                                      o                          ",
    "              x!!!x              xxx                                    ooo                         ",
    "              x   x                                                    xxxxx                        ",
    "              x   x                                                  xx!!!!!xx                      ",
    "              x o x      xxx                                       xx!!!!!!!!!xx                    ",
    "              x o x                                              xx             xx                  ",
    "              x   x                      ooo                   xx                 xx                ",
    "                              xxxx      ooo                  XX                     XX       o      ",
    " @                                     ooo                                                          ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                            x!!!!!x             x!!!!!x                                             ",
    "                            x!!!!!x             x!!!!!x                                             ",
    "                            x!!!!!x             xxxxxxx                                             ",
    "                            xxxxxxx                                                                 ",
    "                                                                                                    ",
    "                                                                                                    "],
    ["                                                                                                 ",
     "                                                                                                 ",
     "                                                                                                 ",
     "                                                                                                 ",
     "                                                                                                 ",
     "                  xxxxxxxxxxxx                                                                   ",
     "                  x          x                                                                   ",
     "                  xooooooo   x                                                                   ",
     "                  xxxxxxxx   x                                           oo                      ",
     "                  x          x                                          oooo           o         ",
     "                  x          x                                        xxxxxxxx       o   o       ",
     "                  x        xxx                                        x!!!!!!x                   ",
     "                  x          x                xxxxxxxxx     xxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxx",
     "                  xxx        x                x       x!!!!!x                                    ",
     "                                          x x x       x!!!!!x                                    ",
     "                        xxx                   x       x!!!!!x                                    ",
     " @                                            x       x!!!!!x                                    ",
     "xxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxx                                    ",
     "        x!!!!!x                                                                                  ",
     "        x!!!!!x                                                                                  ",
     "        x!!!!!x                                                                                  ",
     "        x!!!!!x                                                                                  ",
     "        xxxxxxx                                                                                  ",
     "                                                                                                 "],
  ["                                           ",
   "      x     x                              ",
   "       x   x                               ",
   "        x x    xxx   x   x                 ",
   "         x    x   x  x   x                 ",
   "         x    x   x  x   x                 ",
   "         x     xxx    xxx                  ",
   "                                           ",
   "                           x               ",
   "                x          x               ",
   "  x         x        xxx   x               ",
   "   x   x   x    x   x   x  x               ",
   "    x x x x     x   x   x                  ",
   "     x   x      x   x   x  x               ",
   "                                           ",
   "                                           "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
